Memory system
BESM-Consortium/BESM-666 pull request #23
Opened 2023-09-09 23:43 UTC by mmamayka

Adds
- `PageAllocator` class for fast allocation of simulated device memory pages
- `PhysMem` class with it builder `PhysMemBuilder` that implements physical memory space of size 2^64 keeping simulated device physical memory pages to target device memory mapping in RB tree.
- Simple unit tests for both classes
- A bit of misc functions & interfaces

2023-09-10 09:36 UTC, c71n93 commented on CMakeLists.txt
Could you please add `set(CMAKE_CXX_STANDARD 17)`. My default compiler C++ standard is 11 so project doesn't compile without it. I think it is better to explicitly set C++ standard.

2023-09-10 19:32 UTC, mmamayka commented on CMakeLists.txt
Yes, I can, but in separate branch. Please, tune your compiler manually for testing current PR

2023-09-13 17:46 UTC, c71n93 commented on CMakeLists.txt
@mmamayka why?

2023-09-14 11:49 UTC, levBagryansky requested changes
@mmamayka please check this out

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/mmap-wrapper.hpp
> +// This wraps will be used in unit test. I really don't know, how to
@mmamayka please add todo here

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/mmap-wrapper.hpp
> +void *besm666_mmap(void *addr, size_t length, int prot, int flags, int fd,
Why `_m` mean? Why not `besm666_map`?

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/mmap-wrapper.hpp
> +int besm666_munmap(void *addr, size_t length);
@mmamayka maybe `besm666_m_unmap`?

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/page-allocator.hpp
> +    static constexpr size_t DefaultChunkSize = 1024 * 1024 + 2; // 2MB
1024 * 1024 * 2?

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/page-allocator.hpp
> +    PageAllocator(size_t chunkSize, size_t pageSize);
@mmamayka Seems we can write `PageAllocator(const size_t chunkSize = PageAllocator.DefaultChunkSize, const size_t pageSize);` here

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/page-allocator.hpp
> +    size_t chunkSize_;
@mmamayka this fields must be const

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/page-allocator.hpp
> +    class Chunk;
@mmamayka is this class public? Why not private?

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/phys-mem.hpp
> +        RV64Size id;
@mmamayka mutable fields?

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/phys-mem.hpp
> +    struct Page {
@mmamayka why not private?

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/phys-mem.hpp
> +    Pagemap pagemap_;
@mmamayka I think we can just make this field 
`std::set<Page, std::less<>> pagemap_`. defining new type via using is redundant as for me since we don't use the type anywhere more.

2023-09-14 11:49 UTC, levBagryansky commented on include/besm-666/memory/phys-mem.hpp
> +bool operator<(PhysMemPagemap::Page lhs, PhysMemPagemap::PageId rhs);
@mmamayka It seems weird and unexpected to compare `Page` and `PageId`. Let's get rid of it

2023-09-15 11:17 UTC, levBagryansky requested changes

2023-09-15 11:17 UTC, levBagryansky commented on src/memory/phys-mem.cpp
> +PhysMem PhysMemBuilder::build() { return PhysMem(std::move(pagemap_)); }
@mmamayka please throw exception in case of the second `build`

2023-09-15 11:17 UTC, levBagryansky commented on src/memory/page-allocator.cpp
> +    std::cout << size_ << ' ' << pageSize_ << std::endl;
@mmamayka cout?

2023-09-15 11:24 UTC, mmamayka commented on include/besm-666/memory/mmap-wrapper.hpp
> +void *besm666_mmap(void *addr, size_t length, int prot, int flags, int fd,
Have you even seen an implementation of `besm666_mmap` method?! It calls `mmap` system call directly and does nothing more. `mmap` means "memory map". `munmap` means "memory unmap". There are POSIX syscall names, so I won't rename them and this functions too.

2023-09-15 11:24 UTC, mmamayka commented on include/besm-666/memory/mmap-wrapper.hpp
> +int besm666_munmap(void *addr, size_t length);
Above

2023-09-15 11:25 UTC, mmamayka commented on include/besm-666/memory/page-allocator.hpp
> +    PageAllocator(size_t chunkSize, size_t pageSize);
Erm... You can't set up a default value to non last argument of function/method

2023-09-15 11:26 UTC, mmamayka commented on include/besm-666/memory/page-allocator.hpp
> +    size_t chunkSize_;
`chunks_` can't be const.

2023-09-15 11:27 UTC, mmamayka commented on include/besm-666/memory/page-allocator.hpp
> +    class Chunk;
It allows `std::set` to construct instances of the `Chunk` class.

2023-09-15 11:27 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +        RV64Size id;
What?

2023-09-15 11:28 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +    struct Page {
It allows `std::set` to construct the instances of this class

2023-09-15 11:30 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +bool operator<(PhysMemPagemap::Page lhs, PhysMemPagemap::PageId rhs);
It seems to be used in page searching methods, they won't work without this operators overloading. It's totally expected, because `std::set` has comparator specified as `std::less<>`, that allows comparison of different types in `std::set::find` method.

2023-09-15 11:40 UTC, levBagryansky commented on include/besm-666/memory/phys-mem.hpp
> +bool operator<(PhysMemPagemap::Page lhs, PhysMemPagemap::PageId rhs);
@mmamayka please show the line where we need it, I don't understand

2023-09-15 11:42 UTC, levBagryansky commented on include/besm-666/memory/phys-mem.hpp
> +    struct Page {
@mmamayka maybe `friend`?

2023-09-15 11:43 UTC, levBagryansky commented on include/besm-666/memory/phys-mem.hpp
> +        RV64Size id;
@mmamayka Why is this field mutable, not const?

2023-09-15 11:45 UTC, levBagryansky commented on include/besm-666/memory/page-allocator.hpp
> +    PageAllocator(size_t chunkSize, size_t pageSize);
@mmamayka maybe `PageAllocator(const size_t chunkSize = PageAllocator.DefaultChunkSize, const size_t pageSize = Page.defaultSize);` then to overload the method in case of default values

2023-09-15 12:36 UTC, mmamayka commented on include/besm-666/memory/mmap-wrapper.hpp
> +// This wraps will be used in unit test. I really don't know, how to
Done

2023-09-15 12:38 UTC, mmamayka commented on include/besm-666/memory/page-allocator.hpp
> +    static constexpr size_t DefaultChunkSize = 1024 * 1024 + 2; // 2MB
Done

2023-09-15 12:39 UTC, mmamayka commented on include/besm-666/memory/page-allocator.hpp
> +    PageAllocator(size_t chunkSize, size_t pageSize);
Done

2023-09-15 12:46 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +    struct Page {
Fixed

2023-09-15 12:50 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +    Pagemap pagemap_;
`std::set<Page, std::less<>>::const_iterator` becomes incredibly long type name.

2023-09-15 12:52 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +bool operator<(PhysMemPagemap::Page lhs, PhysMemPagemap::PageId rhs);
`PhysMemPagemap::touchAddress` method, see `auto pageItr = pagemap._find(pageId)`.

2023-09-15 12:56 UTC, mmamayka commented on src/memory/phys-mem.cpp
> +PhysMem PhysMemBuilder::build() { return PhysMem(std::move(pagemap_)); }
`PhysMem` keeps valid state after move

2023-09-15 12:56 UTC, mmamayka commented on src/memory/page-allocator.cpp
> +    std::cout << size_ << ' ' << pageSize_ << std::endl;
Fixed

2023-09-15 12:57 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +        RV64Size id;
There are 2 type definitions, there is no any field

2023-09-15 13:03 UTC, c71n93 commented on include/besm-666/memory/page-allocator.hpp
> + * \brief PagePool class is repsonsible for memory allocation on target
replace `PagePool` by `PageAllocator` in documentation

2023-09-15 13:08 UTC, mmamayka commented on include/besm-666/memory/page-allocator.hpp
> + * \brief PagePool class is repsonsible for memory allocation on target
Fixed

2023-09-15 13:22 UTC, c71n93 commented on src/memory/page-allocator.cpp
> +PageAllocator::Chunk::Chunk(Chunk &&other)
Doesn't the compiler generate identical code? Why do we need to implement it?

2023-09-15 13:24 UTC, c71n93 commented on src/memory/page-allocator.cpp
> +        data_ = rower_ = nullptr;
Isn't this line useless?

2023-09-15 13:27 UTC, c71n93 commented on src/memory/page-allocator.cpp
> +        ;
What is it?

2023-09-15 13:40 UTC, c71n93 commented on src/memory/page-allocator.cpp
> +void *PageAllocator::allocPage() {
Add todo to optimize this method pls

2023-09-15 14:09 UTC, c71n93 commented on src/memory/phys-mem.cpp
> +RV64Size PhysMemPagemap::addr2PageOffset(RV64Ptr address) {
Make this method `const`

2023-09-15 16:26 UTC, mmamayka commented on src/memory/page-allocator.cpp
> +PageAllocator::Chunk::Chunk(Chunk &&other)
By default move constructor is the same as copy constructor

2023-09-15 16:28 UTC, mmamayka commented on src/memory/page-allocator.cpp
> +        ;
Typo) Fixed

2023-09-15 16:31 UTC, mmamayka commented on src/memory/phys-mem.cpp
> +RV64Size PhysMemPagemap::addr2PageId(RV64Ptr address) {
Done

2023-09-15 16:31 UTC, mmamayka commented on src/memory/phys-mem.cpp
> +RV64Size PhysMemPagemap::addr2PageOffset(RV64Ptr address) {
Done

2023-09-15 16:33 UTC, mmamayka commented on src/memory/page-allocator.cpp
> +        data_ = rower_ = nullptr;
It will cause `SIGSEGV` in attempt to access class instance after its destruction. Useless, but safer a bit.

2023-09-15 17:20 UTC, c71n93 commented on src/memory/page-allocator.cpp
> +PageAllocator::Chunk::Chunk(Chunk &&other)
Maybe then you need to explicitly define `Chunk& operator=(Chunk &&rhs)`?

2023-09-15 17:30 UTC, c71n93 commented on src/memory/page-allocator.cpp
> +        data_ = rower_ = nullptr;
[Vladimirov](https://youtu.be/duDyVgMFyug?si=Q-zKbkgQJt3Bd7NP&t=2377)

2023-09-15 22:09 UTC, mmamayka commented on src/memory/page-allocator.cpp
> +void *PageAllocator::allocPage() {
Optimized

2023-09-15 22:49 UTC, levBagryansky approved these changes
@mmamayka LGBT

2023-09-15 22:54 UTC, mmamayka commented
Adds
- PageAllocator class for fast allocation of simulated device memory pages
- PhysMem class with it builder PhysMemBuilder that implements physical memory space of size 2^64 keeping simulated device physical memory pages to target device memory mapping in RB tree.
- Simple unit tests for both classes
- A bit of misc functions & interfaces

2023-09-15 22:56 UTC, merged