#10: Edited instruction struct and introduce decoder
BESM-Consortium/BESM-666 pull request #32
Opened 2023-09-16 18:02 UTC by levBagryansky

Closes #10
Decoder something like skeleton.

2023-09-17 07:35 UTC, mmamayka requested changes
The PoC implementation looks perfect but should be finished before merging

2023-09-17 07:35 UTC, mmamayka commented on include/decoder/decoder.hpp
> +#define R 1
Please, make enum with decoding formats inside the `Decoder` class to avoid preprocessor usage.

2023-09-17 07:35 UTC, mmamayka commented on include/decoder/decoder.hpp
> +namespace besm::decoder {
I think we can reduce namespace name `decoder` to `dec` to avoid very long expressions accessing decoder classes & functions

2023-09-17 07:35 UTC, mmamayka commented on include/decoder/decoder.hpp
> +    constexpr static uint8_t OPCODES[128] = {
In future this array should be made automatically generated. So, It should be extracted to separate header file to make its generation more convenient.

2023-09-17 07:35 UTC, mmamayka commented on include/decoder/decoder.hpp
> +    static besm::Instruction next(const RV64Word word) {
- please, rename this method to something like `parse` because the `Decoder` class does not contain any internal state like iterator, so it is not capable to give the next instruction. It only parser the binary representation.
- please, make this method non-static to make further development of decoder more convenient. There are RV64C extension, that defines 2-bytes instructions. It will require the decoder to have internal state, containing the second half of 4-byte word in future.

2023-09-17 07:35 UTC, mmamayka commented on include/decoder/decoder.hpp
> +        const Opcode opcode = word & 0b01111111;
There is a magic value `0b01111111`. Make it private constant of the decoder class.

2023-09-17 07:35 UTC, mmamayka commented on include/decoder/decoder.hpp
> +        case R:
Please, add `break` to each `case` and `default` statement. It makes extending of `case` statement safer.

2023-09-17 07:35 UTC, mmamayka commented on include/decoder/decoder.hpp
> +            throw std::invalid_argument(
Please, define a separate exception class with name like `IllegalInstruction` inherited from `std::runtime_error` to make further exception catching more convenient (there is hardware exception "Illegal Instruction" in RISCV ISA definition, so I want to save naming coherence between the ISA definition & out implementation proposing this name)

2023-09-17 07:35 UTC, mmamayka commented on test/decoder/decoder_test.cpp
> +TEST(Decoder, decodes_simple_instruction) {
I would propose to test each available instruction but it is a point for discussion.

2023-09-19 10:26 UTC, mmamayka requested changes
Looks really great! But should be polished a bit

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/IllegalOpcodeException.hpp
> +class IllegalOpcodeException : public std::runtime_error {
Please, declare also `char const*` constructor.

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/IllegalOpcodeException.hpp
> +    IllegalOpcodeException()
You can use `std::exception` as a parent class of `IllegalOpcodeException` if you don't want to use `cause` field

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/decoder.hpp
> +constexpr RV64Word OPCODE_MASK = 0b01111111;
I think, this constants should be declared as static private members of `Decoder` class.

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/opcodes-to-format.hpp
> +enum format_t { ILLEGAL, R, I, S, B, U, J };
- Please, rename `format_t` enumeration to something like `Format`
- I think this enumeration should be moved into `Decoder` class private static members

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/opcodes-to-format.hpp
> +constexpr static uint8_t OPCODE2FORMAT[128] = {
I think. this array should be moved into `Decoder` class private static members

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/operations-matrix.hpp
> +struct Cell {
I think, `Cell` should be removed from automatically generated header. So, it should be declared as `Decoder` private static member

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/operations-matrix.hpp
> +constexpr static Cell SUPER_MEGA_MATRIX[128][8] = {
I think, this matrix should be declared as private static member of `Decoder`

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/riscv-types.hpp
> +using RV64Word = uint32_t;
There is already defined unsigned version of `RV64Word` named as `RV64UWord`. Please, use it.

2023-09-19 10:26 UTC, mmamayka commented on test/decoder/decoder_test.cpp
> +    ASSERT_EQ(add_instance.operation, parsed.operation);
Missmatch of operation/register/immidiate is not a fatal error for further test execution. You should use `EXPECT_EQ` here.

2023-09-19 10:26 UTC, mmamayka commented on test/decoder/decoder_test.cpp
> +    besm::dec::Decoder decoder{};
You can defined test fixture with `decoder` & `instruction` field. Also, you can define instruction builder method to reduce code duplication it tests.

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/opcodes-to-format.hpp
> +#pragma once
Please, move this header to `autogen` folder.

2023-09-19 10:26 UTC, mmamayka commented on include/besm-666/decoder/operations-matrix.hpp
> +#pragma once
Please, move this header to `autogen` folder.

2023-09-19 20:38 UTC, levBagryansky commented on include/besm-666/decoder/opcodes-to-format.hpp
> +constexpr static uint8_t OPCODE2FORMAT[128] = {
@mmamayka No, It is used in `SUPER_MEGA_MATRIX` which is used in decoder header. So it should be declared earlier.

2023-09-19 20:41 UTC, levBagryansky commented on test/decoder/decoder_test.cpp
> +    besm::dec::Decoder decoder{};
@mmamayka We don't need instruction builder here because, it will not help.

2023-09-19 20:58 UTC, levBagryansky commented on test/decoder/decoder_test.cpp
> +    besm::dec::Decoder decoder{};
@mmamayka instructions are different in different tests.

2023-09-19 21:39 UTC, levBagryansky commented on include/besm-666/decoder/operations-matrix.hpp
> +struct Cell {
@mmamayka I cannot, because this header uses the `Cell` and Decoder uses `operations-matrix.hpp`.

2023-09-19 21:46 UTC, c71n93 commented on include/besm-666/decoder/decoder.hpp
> +    besm::Instruction parse(const RV64UWord word) const {
I think `word` should be renamed into `ins`

2023-09-19 21:48 UTC, c71n93 commented on include/besm-666/decoder/decoder.hpp
> +        const Cell *cell = &(SUPER_MEGA_MATRIX[opcode][func3]);
`SUPER_MEGA_MATRIX` is a uninformative name

2023-09-19 21:53 UTC, mmamayka commented on test/decoder/decoder_test.cpp
> +    besm::dec::Decoder decoder{};
Okay, it was just a proposal. You can resolve this conversation, it's up to you

2023-09-19 21:53 UTC, mmamayka commented on include/besm-666/decoder/decoder.hpp
> +    besm::Instruction parse(const RV64UWord word) const {
`bytecode` I suppose

2023-09-19 21:54 UTC, levBagryansky commented on include/besm-666/decoder/decoder.hpp
> +        const Cell *cell = &(SUPER_MEGA_MATRIX[opcode][func3]);
@c71n93 please provide more informative. `SUPER_MEGA_MATRIX` is the clearest name as for me:)

2023-09-19 21:55 UTC, c71n93 commented on include/besm-666/decoder/decoder.hpp
> +    static inline Instruction parse_R(const RV64UWord word, const Opcode opcode,
About `word` above

2023-09-19 22:10 UTC, c71n93 approved these changes

2023-09-19 22:22 UTC, mmamayka submitted a review, later dismissed
LGBTQ++11

2023-09-20 09:14 UTC, c71n93 commented on test/decoder/decoder_test.cpp
> +TEST(Decoder, decodes_simple_instruction) { EXPECT_TRUE(true); }
delete

2023-09-20 09:34 UTC, c71n93 approved these changes

2023-09-20 09:39 UTC, merged