Executor
BESM-Consortium/BESM-666 pull request #36
Opened 2023-09-18 18:23 UTC by mmamayka

Adds instruction executor stub

2023-09-18 20:36 UTC, c71n93 commented on include/besm-666/reg/rf.hpp
>      static constexpr size_t Size = 33;
why size is not `const`?

2023-09-18 21:00 UTC, c71n93 commented on include/besm-666/exec/executor.hpp
> +    reg::GPRF &gprf_;
Fix refference

2023-09-18 21:15 UTC, c71n93 commented on test/exec/RV64I-executor-tests.cpp
> +}
Are you planning to add tests to other exec functions

2023-09-19 07:36 UTC, c71n93 commented on src/exec/executor.cpp
> +        break;
Add default temporarily

2023-09-19 10:30 UTC, mmamayka commented on test/exec/RV64I-executor-tests.cpp
> +}
Of course, they will be added a bit later

2023-09-19 10:31 UTC, mmamayka commented on src/exec/executor.cpp
> +        break;
Lack of default section makes compiler to show warning with list of unimplemented instructions

2023-09-19 10:31 UTC, mmamayka commented on include/besm-666/reg/rf.hpp
>      static constexpr size_t Size = 33;
Typo, will be fixed

2023-09-19 10:31 UTC, mmamayka commented
Do everybody agree with current executors implementation style?

2023-09-19 17:41 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    reg::GPRF &gprf_;
Fixed

2023-09-19 17:41 UTC, mmamayka commented on include/besm-666/reg/rf.hpp
>      static constexpr size_t Size = 33;
Fixed

2023-09-19 17:46 UTC, c71n93 commented on src/exec/executor.cpp
> +        break;
> Lack of default section makes compiler to show warning with list of unimplemented instructions

very smart

2023-09-19 17:48 UTC, c71n93 commented
> Do everybody agree with current executors implementation style?

Yes, style is good. But I checked implementation only of half of instructions.

2023-09-19 21:25 UTC, levBagryansky commented on include/besm-666/exec/executor.hpp
> +    void exec_ADDI(Instruction instr);
@mmamayka could you plesae mark it const if you removed const from `Finstruction`'s field

2023-09-19 21:36 UTC, levBagryansky requested changes
@mmamayka  Looks good. I'll check tests later

2023-09-19 21:36 UTC, levBagryansky commented on include/besm-666/instruction.hpp
> +    RV64UDWord immidiate;
@mmamayka use `Immidiate` which you have already reassign

2023-09-19 21:48 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    void exec_ADDI(Instruction instr);
What to mark?

2023-09-19 22:15 UTC, levBagryansky commented on include/besm-666/exec/executor.hpp
> +    void exec_ADDI(Instruction instr);
@mmamayka I mean `const Instruction instr`. Does `exec_ADDI` change `Executor`?

2023-09-19 22:17 UTC, mmamayka commented on test/exec/RV64I-executor-tests.cpp
> +}
Done

2023-09-19 22:17 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    void exec_ADDI(Instruction instr);
Yep, it changes `GPRF` state

2023-09-20 10:06 UTC, mmamayka commented on src/exec/executor.cpp
> +        break;
All known insns are implemented now

2023-09-20 10:12 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    void exec_ADDI(Instruction instr);
Fixed

2023-09-20 10:34 UTC, levBagryansky requested changes
@mmamayka executor-tests is to review then)

2023-09-20 10:34 UTC, levBagryansky commented on test/exec/simple-programs.cpp
> +/*
@mmamayka What is going here?

2023-09-20 10:34 UTC, levBagryansky commented on test/util/bit-magic-tests.cpp
> +TEST(SignExtend, NegativeValue) {
@mmamayka please add the test where `uint v = 0b1111` and SignBits = 3

2023-09-20 12:04 UTC, mmamayka commented on test/util/bit-magic-tests.cpp
> +TEST(SignExtend, NegativeValue) {
It is the same test as `NegativeValue`. Please, describe what corner case you want to be tested?

2023-09-20 12:06 UTC, mmamayka commented on test/exec/simple-programs.cpp
> +/*
The `EXPECT_EQ` checks that the result, placed in `x1` register, is equal to sum of range `0..5`.

2023-09-20 12:58 UTC, levBagryansky commented on test/util/bit-magic-tests.cpp
> +TEST(SignExtend, NegativeValue) {
In this test `7=0b111` with 3 '1' and SingnBits is `3` too. I'd like to be sure that the result with `0b1111` will be the same because 3 repeats in this test several times.

2023-09-20 16:02 UTC, levBagryansky commented on test/exec/simple-programs.cpp
> +/*
@mmamayka I don't get it. Could you leave a describing here? Maybe alternative "c" code in comment.

2023-09-20 16:04 UTC, levBagryansky commented on test/exec/RV64I-executor-tests.cpp
> +    void LoadImm12(Register rd, RV64DWord val) {
@mmamayka Why 12? What does this function?

2023-09-20 16:07 UTC, levBagryansky commented on test/exec/RV64I-executor-tests.cpp
> +    void SetupInstrIS(InstructionOp op, Register rd, Register rs1,
@mmamayka `SetupInstrIS` is inappropriate name because `S` means either `format` and `sign`.

2023-09-21 14:18 UTC, mmamayka commented on test/exec/RV64I-executor-tests.cpp
> +    void LoadImm12(Register rd, RV64DWord val) {
It loads 12 bit wide immidiate value from `val` to register `rd`.

2023-09-21 14:19 UTC, mmamayka commented on test/exec/RV64I-executor-tests.cpp
> +    void SetupInstrIS(InstructionOp op, Register rd, Register rs1,
The first capital letter `I` means I-format, the second capital `S` means signed

2023-09-21 14:20 UTC, mmamayka commented on test/exec/simple-programs.cpp
> +/*
There is a "c" alternative code in comment above the test

2023-09-21 16:19 UTC, levBagryansky commented on test/exec/RV64I-executor-tests.cpp
> +    void SetupInstrIS(InstructionOp op, Register rd, Register rs1,
@mmamayka I get it and it is not clear as for me. Maybe `SetupInstrISigned`?

2023-09-21 17:14 UTC, levBagryansky commented on test/exec/simple-programs.cpp
> +        // PC = 28 - add first factor to result is bit is set
@mmamayka typo? `if bit is set`*?

2023-09-21 18:23 UTC, levBagryansky commented on test/util/bit-magic-tests.cpp
> +TEST(SignExtend, NegativeValue) {
@mmamayka up to you

2023-09-21 22:36 UTC, mmamayka commented on test/exec/simple-programs.cpp
> +        // PC = 28 - add first factor to result is bit is set
I do comparison with `x0` in `BEQ`, so it's not a typo.

2023-09-21 22:43 UTC, mmamayka commented on test/exec/RV64I-executor-tests.cpp
> +    void SetupInstrIS(InstructionOp op, Register rd, Register rs1,
Fixed

2023-09-21 23:10 UTC, mmamayka commented on test/util/bit-magic-tests.cpp
> +TEST(SignExtend, NegativeValue) {
Done

2023-09-22 07:08 UTC, levBagryansky approved these changes
@mmamayka Thanks

2023-09-22 11:02 UTC, c71n93 approved these changes

2023-09-22 11:07 UTC, merged