Elf Loader (Parser)
BESM-Consortium/BESM-666 pull request #44
Opened 2023-09-21 09:04 UTC by c71n93

Closes #9 

Adds:
- `ElfParser` class for parsing elf files.
- Implements `loadElf` method of `PhysMemBuilder` class
- Unit tests

2023-09-21 13:38 UTC, levBagryansky requested changes

2023-09-21 13:38 UTC, levBagryansky commented on include/besm-666/utils/elf-parser.hpp
> +        Encoding = ELFIO::ELFDATA2LSB,
@c71n93 why not ELFIO::LITTLE_ENDIAN, or ELFIO::LENDIAN?

2023-09-21 13:38 UTC, levBagryansky commented on include/besm-666/utils/elf-parser.hpp
> +        Arch = ELFIO::EM_RISCV
@c71n93 EM? Do not eat it)

2023-09-21 13:38 UTC, levBagryansky commented on include/besm-666/utils/elf-parser.hpp
> +    void checkRequirements();
@c71n93 `void checkRequirements() const;`

2023-09-21 13:38 UTC, levBagryansky commented on test/elfgen/CMakeLists.txt
> +)
@c71n93 just emply library?

2023-09-21 13:42 UTC, c71n93 commented on include/besm-666/utils/elf-parser.hpp
> +        Encoding = ELFIO::ELFDATA2LSB,
@levBagryansky  It's ELFIO internal constant

2023-09-21 13:42 UTC, c71n93 commented on include/besm-666/utils/elf-parser.hpp
> +        Arch = ELFIO::EM_RISCV
@levBagryansky It's ELFIO internal constant

2023-09-21 13:43 UTC, c71n93 commented on test/elfgen/CMakeLists.txt
> +)
@levBagryansky I added in `.` as `target_include_directories`

2023-09-21 14:13 UTC, mmamayka requested changes
Looks good, but should be polished a bit

2023-09-21 14:13 UTC, mmamayka commented on include/besm-666/util/elf-parser.hpp
> +class ElfParser final {
`ElfParser` contains non-copyable field `std::vector<LoadableSegment>`, so, please, mark the `ElfParser` class as non-copyable to make compiler error log more human readable.

2023-09-21 14:13 UTC, mmamayka commented on include/besm-666/util/elf-parser.hpp
> +    enum Requirements {
I suppose, `Requirements` should be public structure with `fileClass`, `encoding` and `arch` fields to make the `ElfParser` more customizable. The `Requirements` should be passed to ctor and checked after elf parsing.

Also, I suppose to add public static instance of `Requirements` structure, that describes RISCV standalone bare-metal ELF build used in out simulator.

2023-09-21 14:13 UTC, mmamayka commented on include/besm-666/util/elf-parser.hpp
> +class BadElf : public std::runtime_error {
I suppose to rename this exception to `InvalidELFFormat` to throw it if ELF structure is invalid (`elfio` raises a error). And also to add `UnvailableELFRequirements` error to separate invalid elf format error and mismatch of requirements error.

2023-09-21 14:13 UTC, mmamayka commented on include/besm-666/util/elf-parser.hpp
> +    BadElf(const std::string &msg);
Please, add also `char const*` ctor

2023-09-21 17:16 UTC, levBagryansky submitted a review, later dismissed

2023-09-22 13:47 UTC, mmamayka approved these changes
LGBTQ++14

2023-09-22 15:51 UTC, levBagryansky requested changes
@c71n93 please check

2023-09-22 15:51 UTC, levBagryansky commented on include/besm-666/util/elf-parser.hpp
> +    createParser(const std::filesystem::path &elfPath);
@c71n93 I don't think it's ok that `interface` knows about its inheritors. Let's make this method belonging to `ElfParser` class

2023-09-22 16:05 UTC, levBagryansky commented on include/besm-666/util/elf-parser.hpp
> +    createParser(const std::filesystem::path &elfPath);
@mmamayka WDYT?

2023-09-22 17:11 UTC, levBagryansky approved these changes

2023-09-22 17:29 UTC, mmamayka approved these changes
LGBTQ++17

2023-09-22 17:45 UTC, merged