Add Memory stub
BESM-Consortium/BESM-666 pull request #47
Opened 2023-09-21 23:53 UTC by mmamayka

Adds trivial memory implementation with mapping 1:1 (VA == PA)

2023-09-22 10:27 UTC, levBagryansky requested changes
@mmamayka please check

2023-09-22 10:27 UTC, levBagryansky commented on include/besm-666/memory/memory.hpp
> +    Memory(PhysMem &&pMem);
@mmamayka  Single-argument constructors must be marked `explicit` to avoid unintentional implicit conversions

2023-09-22 10:27 UTC, levBagryansky commented on include/besm-666/memory/memory.hpp
> +    RV64UDWord loadDWord(RV64Ptr address) const;
@mmamayka can be [[nodiscard]]

2023-09-22 10:27 UTC, levBagryansky commented on include/besm-666/memory/memory.hpp
> +    friend class MemoryBuilder;
@mmamayka can be public

2023-09-22 10:28 UTC, levBagryansky commented on include/besm-666/memory/memory.hpp
> +    RV64UDWord loadDWord(RV64Ptr address) const;
@mmamayka up to you

2023-09-22 12:27 UTC, mmamayka commented on include/besm-666/memory/memory.hpp
> +    Memory(PhysMem &&pMem);
The `Memory` class does not have default constructor, so ctor mismatch is impossible.

2023-09-22 12:27 UTC, mmamayka commented on include/besm-666/memory/memory.hpp
> +    RV64UDWord loadDWord(RV64Ptr address) const;
Later, will fix it after release

2023-09-22 12:29 UTC, mmamayka commented on include/besm-666/memory/memory.hpp
> +    friend class MemoryBuilder;
This method will contain address translation algorithm (Virtual address to Physical address). There are no reasons now to use it in Hart or other parst, so it is private.

2023-09-22 14:52 UTC, c71n93 commented on include/besm-666/memory/mmu.hpp
> +    RV64UChar loadByte(RV64Ptr address) const;
why don't you use something like this
```
template <typename T>
requires std::is_same_v<T, RV64UChar> || std::is_same_v<T, RV64UHWord> ||
         std::is_same_v<T, RV64UWord> || std::is_same_v<T, RV64UDWord>
T MMU::load(RV64Ptr address) const {
    RV64Ptr paddr = this->translate(address);
    return pMem_.load<T>(paddr);
}
```
It's shorter and more explicit.

2023-09-22 15:06 UTC, c71n93 commented on include/besm-666/memory/mmu.hpp
> +    PhysMem &pMem_;
external reference

2023-09-22 15:15 UTC, c71n93 commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
what do you think about renaming `touchAddress` into `translateOrAllocate`?

2023-09-22 15:38 UTC, mmamayka commented on include/besm-666/memory/mmu.hpp
> +    RV64UChar loadByte(RV64Ptr address) const;
I would prefer explicit type declaration to avoid types mismatch in executor.

2023-09-22 15:38 UTC, mmamayka commented on include/besm-666/memory/mmu.hpp
> +    PhysMem &pMem_;
Yep, but I will be safe in further usage

2023-09-22 15:39 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
Very very long name I think. I have selected this name because there is an analogy with `touch` bash command, that creates file if it is absent or does nothing otherwise.

2023-09-22 16:10 UTC, levBagryansky commented on include/besm-666/memory/memory.hpp
> +    friend class MemoryBuilder;
@mmamayka I asked about `friend class MemoryBuilder`

2023-09-22 16:17 UTC, c71n93 commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
@mmamayka This is unclear logic, not everyone gets it. Names should be clear and understandable in the first place, and brief in the second.

2023-09-22 16:22 UTC, levBagryansky commented on include/besm-666/memory/memory.hpp
> +    Memory(PhysMem &&pMem);
@mmamayka When programmer add dafault ctor, he will forgot to edit this

2023-09-22 16:27 UTC, c71n93 commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
@mmamayka Nevermind, I thought again, it's acceptable name.

2023-09-22 16:56 UTC, c71n93 commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
@mmamayka But rename `translate` to `translateAddress`, please.

2023-09-22 17:31 UTC, mmamayka commented on include/besm-666/memory/memory.hpp
> +    friend class MemoryBuilder;
There is no difference

2023-09-22 17:48 UTC, mmamayka commented on include/besm-666/memory/mmu.hpp
> +    PhysMem &pMem_;
`shared_ptr<PhysMem>` used instead.

2023-09-22 18:09 UTC, mmamayka commented on include/besm-666/memory/memory.hpp
> +    Memory(PhysMem &&pMem);
Fixed

2023-09-22 18:14 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
Done

2023-09-26 14:49 UTC, c71n93 commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
@mmamayka where?

2023-09-26 16:51 UTC, mmamayka commented on include/besm-666/memory/phys-mem.hpp
> +    void const *translate(RV64Ptr address) const;
Definitely done =)

2023-09-26 17:47 UTC, levBagryansky approved these changes
@mmamayka nice, thanks

2023-09-26 19:25 UTC, c71n93 approved these changes

2023-09-26 21:28 UTC, merged