Decoder j
BESM-Consortium/BESM-666 pull request #52
Opened 2023-09-22 23:19 UTC by levBagryansky

2023-09-24 21:45 UTC, levBagryansky commented
@mmamayka please check

2023-09-25 21:29 UTC, mmamayka requested changes
Looks good, but need to be polished a bit

2023-09-25 21:29 UTC, mmamayka commented on include/besm-666/autogen/operations-matrix.hpp
> +        {I, NON_OP},
What `NON_OP` means? In RICSV it's a pseudo instruction encoded as `add x0, x0, x0`, so it can't be emitted by decoder.

2023-09-25 21:29 UTC, mmamayka commented on src/decoder/decoder.cpp
> +        .immidiate = (bytecode & IMM_MASK),
Please, do this using `ExtractBits` method from bits magic header

2023-09-25 21:29 UTC, mmamayka commented on src/decoder/decoder.cpp
> +    const auto rd = static_cast<Register>((bytecode & RD_MASK) >> RD_SHIFT);
There is a specified method `ExtractBits` in bit magic header

2023-09-25 21:29 UTC, mmamayka commented on src/decoder/decoder.cpp
> +    const auto rs1 = static_cast<Register>((bytecode & RS1_MASK) >> RS1_SHIFT);
There is a specified method ExtractBits in bit magic header

2023-09-25 21:29 UTC, mmamayka commented on src/decoder/decoder.cpp
> +    const uint8_t func3 = (bytecode & FUNC3_MASK) >> FUNC3_shift;
Same stuff. Please, use this method instead of manual mask calculation in all cases

2023-09-25 21:29 UTC, mmamayka commented on src/decoder/decoder.cpp
> +    case 0b0001111:
Define opcodes constants to get rid of magic numbers

2023-09-26 10:00 UTC, levBagryansky commented on include/besm-666/autogen/operations-matrix.hpp
> +        {I, NON_OP},
@mmamayka `NON_OP` means `Not an operation`. you can suggest another name

2023-09-26 10:05 UTC, mmamayka commented on include/besm-666/autogen/operations-matrix.hpp
> +        {I, NON_OP},
I would suggest another name because the current is strongly associates with `nop` instruction. Could we call it, for example, `ILLEGAL` or `INV_OP`?

2023-09-26 10:17 UTC, levBagryansky commented on src/decoder/decoder.cpp
> +    case 0b0001111:
@mmamayka Name for this number will be `FENCE_OR_FENCETCO_OR_PAUSE`. It is even worse if you ask me. When another instruction with the same opcode will be added we should rename this constant again despite it is already unreadable.

2023-09-26 10:19 UTC, levBagryansky commented on src/decoder/decoder.cpp
> +    case 0b0001111:
@mmamayka I'd like define repeating constants only.

2023-09-26 14:34 UTC, mmamayka commented on src/decoder/decoder.cpp
> +    case 0b0001111:
> @mmamayka Name for this number will be `FENCE_OR_FENCETCO_OR_PAUSE`. It is even worse if you ask me. When another instruction with the same opcode will be added we should rename this constant again despite it is already unreadable.

No, the opcode names are defined in RISCV ISA description. It will have name `MISC_MEM` in your example.

2023-09-26 18:22 UTC, levBagryansky commented on include/besm-666/autogen/operations-matrix.hpp
> +        {I, NON_OP},
@mmamayka done

2023-09-26 19:25 UTC, levBagryansky commented on src/decoder/decoder.cpp
> +    case 0b0001111:
@mmamayka done

2023-09-26 21:30 UTC, mmamayka approved these changes
LGBTQ++

Please, resolve all conversations before merging

2023-09-28 13:04 UTC, c71n93 approved these changes

2023-09-28 13:05 UTC, merged