Memory exec integration
BESM-Consortium/BESM-666 pull request #55
Opened 2023-09-26 16:47 UTC by mmamayka

Implements LD/ST instructions simulation (need to be tested)

2023-09-28 17:26 UTC, c71n93 commented on include/besm-666/exec/executor.hpp
>      // Will be implemented after memory system release
remove coment

2023-09-28 17:33 UTC, c71n93 commented on src/exec/executor.cpp
> +    RV64UDWord extendedValue = util::SignExtend<RV64UDWord, 8>(value);
use static_cast

2023-09-28 17:33 UTC, c71n93 commented on src/exec/executor.cpp
> +    RV64UDWord extendedValue = util::SignExtend<RV64UDWord, 16>(value);
use static_cast

2023-09-28 17:34 UTC, c71n93 commented on src/exec/executor.cpp
> +    RV64UDWord extendedValue = util::SignExtend<RV64UDWord, 32>(value);
use static_cast

2023-09-28 17:37 UTC, levBagryansky requested changes
@mmamayka Looks good but there are several ways to improve it

2023-09-28 17:37 UTC, levBagryansky commented on include/besm-666/exec/executor.hpp
> +    void exec_LD(Instruction const instr);
@mmamayka please make `Instruction`s not `const` in all these methods here. It does not make sense:
Parameter 'instr' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions

2023-09-28 17:37 UTC, levBagryansky commented on include/besm-666/exec/executor.hpp
> +    Executor(mem::MMU::SPtr mmu) : mmu_(mmu) {}
@mmamayka please make it 
1) `explicit Executor`
2)  `: mmu_(std::move(mmu)) {}`

2023-09-28 17:37 UTC, levBagryansky commented on include/besm-666/memory/mmu.hpp
> +    explicit MMU(PhysMem::SPtr pMem) : pMem_(pMem) {}
@mmamayka What do you think about `explicit MMU(PhysMem::SPtr pMem) : pMem_(std::move(pMem)) {}`

2023-09-28 17:56 UTC, levBagryansky commented on include/besm-666/exec/executor.hpp
> +    Executor(mem::MMU::SPtr mmu) : mmu_(mmu) {}
@mmamayka 1) up to you

2023-09-28 19:17 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    void exec_LD(Instruction const instr);
You have requested constantness of this parameters previously..... -__-

2023-09-28 19:18 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    Executor(mem::MMU::SPtr mmu) : mmu_(mmu) {}
What reason to use `std::move` in this context?

2023-09-28 19:19 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
>      // Will be implemented after memory system release
Done

2023-09-28 19:22 UTC, mmamayka commented on src/exec/executor.cpp
> +    RV64UDWord extendedValue = util::SignExtend<RV64UDWord, 8>(value);
Done

2023-09-28 19:22 UTC, mmamayka commented on src/exec/executor.cpp
> +    RV64UDWord extendedValue = util::SignExtend<RV64UDWord, 16>(value);
Done

2023-09-28 19:22 UTC, mmamayka commented on src/exec/executor.cpp
> +    RV64UDWord extendedValue = util::SignExtend<RV64UDWord, 32>(value);
Done

2023-09-28 19:30 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    Executor(mem::MMU::SPtr mmu) : mmu_(mmu) {}
DONE!

2023-09-28 19:30 UTC, mmamayka commented on include/besm-666/memory/mmu.hpp
> +    explicit MMU(PhysMem::SPtr pMem) : pMem_(pMem) {}
Done!

2023-09-28 19:31 UTC, mmamayka commented on include/besm-666/exec/executor.hpp
> +    void exec_LD(Instruction const instr);
I would ignore this to save definition & declaration equal

2023-09-28 21:46 UTC, levBagryansky approved these changes

2023-09-29 06:04 UTC, c71n93 approved these changes

2023-09-29 10:25 UTC, merged