E2E Testing
BESM-Consortium/BESM-666 pull request #60
Opened 2023-10-02 00:04 UTC by mmamayka

The PR reworks current simulator build system to make it capable running e2e tests. 

It adds support of building the single project parts with multiple toolchains with a `ExternalProject` hack (?). See here: https://discourse.cmake.org/t/using-multiple-toolchains-in-the-same-project/1505. We need this to run e2e test that should be build with RISCV arch.

Also it adds dummy e2e test that can be run manually (it's temporary I believe)

2023-10-02 14:02 UTC, levBagryansky commented
@mmamayka tests fail

2023-10-02 14:05 UTC, mmamayka commented
> @mmamayka tests fail


Yep, thanks. I'm working on fixes

2023-10-02 18:59 UTC, levBagryansky commented on CMakeLists.txt
> +    enable_testing()
@mmamayka This command enables all tests, it means the same as 89th line. Is it?

2023-10-02 18:59 UTC, levBagryansky commented on Makefile
> +	cmake -S $(PWD) -B $(PWD)/$(BUILD_DIR)
@mmamayka lets add `-DBESM666_TEST_WITH_VALGRIND=OFF` to avoid building valgrind tests, for example
```
make build-val
make build
```

2023-10-02 19:20 UTC, mmamayka commented on Makefile
> +	cmake -S $(PWD) -B $(PWD)/$(BUILD_DIR)
They will be built only if `BESM666_TEST_WITH_VALGRIND` **defined**. So, there is not reason to set up it to `OFF`.

2023-10-02 19:27 UTC, mmamayka commented on CMakeLists.txt
> +    enable_testing()
It enables testing for e2e test built for RISCV architecture. There are 2 states in CMake building script
- build the simulator and unit tests for x86-64 triggered by defining `BESM666__SIMULATOR_BUILD`
- build e2e tests for RISCV triggered by defining `BESM666__E2E_TESTS_BUILD`
This 2 states invoked as external project consequently by the script part in `NOT BESM666__PARENT_BUILD` branch . This need to achieve capability of building different parts of project (the simulator and e2e tests in our case) with different toolchains, because CMake does not support this kind of configuration by default. So, we are using a dirty hack a bit.

So, in conclusion, we need to enable testing in different branches for different purposes =).

2023-10-03 08:47 UTC, c71n93 commented on CMakeLists.txt
> +    VERSION 1.0.0
Mb 0.1.0? This version don't looks like it can be released.

2023-10-03 08:51 UTC, levBagryansky requested changes
@mmamayka please check valgriand tests are passing

2023-10-03 08:51 UTC, levBagryansky commented on README.md
> +mkdir BESM-666
@mmamayka What about adding dedicated script for it

2023-10-03 12:39 UTC, mmamayka commented on CMakeLists.txt
> +    VERSION 1.0.0
This version is about to release. The next 2 PRs will fix all known errors & validate the simulator pipeline. So, let's leave it as is.

2023-10-03 12:43 UTC, mmamayka commented on README.md
> +mkdir BESM-666
Just copy and paste it, because
- I don't want to add RISCV toolchain in third party dependencies. 
- This commands sequence will be executed once during project setting up
- The root folder of this building script differs from the BESM-666 root folder

So, I suppose to avoid development of script using BESM-666 root parent directory

2023-10-03 15:49 UTC, c71n93 commented on Makefile
> +		-DBESM666_RISCV_SYSROOT=$(RISCV_SYSROOT)
Could you make some `if` statement on `-DBESM666_RISCV_SYSROOT`? Because in root cmake you checking this:
```
if(DEFINED BESM666_WITH_E2E_TESTS AND NOT DEFINED BESM666_RISCV_SYSROOT)
    message(FATAL_ERROR "BESM666_RISCV_SYSROOT should be defined")
endif()
```
But here you are just passing default value, that is most likely incorrect. I think we need to print error, if someone doesn't pass `RISCV_SYSROOT` value.

2023-10-03 15:49 UTC, c71n93 commented on Makefile
> +		-DBESM666_RISCV_SYSROOT=$(RISCV_SYSROOT)
And this error will be printed by cmake.

2023-10-03 17:21 UTC, levBagryansky approved these changes
@mmamayka

2023-10-03 17:29 UTC, c71n93 approved these changes

2023-10-03 17:32 UTC, merged