Old Makefile functionaliy
BESM-Consortium/BESM-666 pull request #63
Opened 2023-10-04 09:13 UTC by c71n93

- Returned `init` target to `Makefile`
- Edited `all` target

2023-10-05 10:05 UTC, levBagryansky submitted a review, later dismissed
@c71n93 Thanks

2023-10-11 02:19 UTC, mmamayka requested changes

2023-10-11 02:19 UTC, mmamayka commented on Makefile
> +	git submodule update
`git submodule update --init --recursive` is a proper command

2023-10-11 08:48 UTC, c71n93 commented
@mmamayka @levBagryansky check

2023-10-11 14:49 UTC, levBagryansky approved these changes

2023-10-12 16:55 UTC, mmamayka approved these changes
LGBT

2023-10-12 17:05 UTC, merged