RAM
BESM-Consortium/BESM-666 pull request #68
Opened 2023-10-16 17:43 UTC by mmamayka

Refactored all memory system, added
- `RAM` class inheriting from `IPhysMemDevice` interface representing random access memory
- `PhysMem` class hold address ranges of all MMIO & RAM devices now
- Configuration options & knobs for memory system
- Standalone runner support of `a0` validation

2023-10-19 14:56 UTC, c71n93 commented on include/besm-666/memory/phys-mem-device.hpp
> +    virtual std::pair<void const *, size_t>
what is this for?

2023-10-19 14:57 UTC, c71n93 commented on include/besm-666/memory/phys-mem-device.hpp
> +    virtual std::pair<void const *, size_t>
cringe, nevermind

2023-10-19 15:38 UTC, c71n93 commented on src/memory/phys-mem.cpp
> +std::vector<PhysMem::DeviceDescriptor> PhysMem::getDevices() const {
I don't get where do we need this function? As I understand only `PhysMem` should know about devices which are available to it. So why do we need this funciton and `DeviceDescriptor`?

2023-10-19 15:48 UTC, c71n93 requested changes

2023-10-19 15:48 UTC, c71n93 commented on src/memory/phys-mem.cpp
> +            throw MappingIntersection("Invalid mapping");
Make this message more infromative, please. For example: "Invalid mapping: device with address range {range} already mapped"

2023-10-19 15:56 UTC, c71n93 requested changes

2023-10-19 15:56 UTC, c71n93 commented on include/besm-666/memory/ram.hpp
> +    virtual ~RAM() {}
Virtual destructor in a final class? Why?

2023-10-19 16:26 UTC, c71n93 requested changes

2023-10-19 16:26 UTC, c71n93 commented on include/besm-666/memory/ram.hpp
> +    std::pair<void *, size_t> getHostAddress(RV64Ptr address) override;
Make different names for these methods, please. Current naming is confusing.

2023-10-19 16:56 UTC, c71n93 reviewed
I think, there are too few memory tests. No method from the RAM class is called directly from unit tests. @mmamayka WDYT?

2023-10-19 20:45 UTC, mmamayka commented on src/memory/phys-mem.cpp
> +std::vector<PhysMem::DeviceDescriptor> PhysMem::getDevices() const {
Probably, some plugin would like to look at devices state. It made for more flexible plugins support

2023-10-19 20:46 UTC, mmamayka commented on include/besm-666/memory/mmu.hpp
> +    std::pair<void const *, size_t> getHostAddress(RV64Ptr address) const;
What?

2023-10-19 21:19 UTC, c71n93 commented on src/memory/phys-mem.cpp
> +std::vector<PhysMem::DeviceDescriptor> PhysMem::getDevices() const {
@mmamayka okay, make sence

2023-10-20 21:17 UTC, mmamayka commented on include/besm-666/memory/phys-mem-device.hpp
> +    CreateRAM(size_t ramSize, size_t ramPageSize, size_t ramChunkSize);
Fixed

2023-10-20 21:24 UTC, mmamayka commented on src/memory/phys-mem.cpp
> +            throw MappingIntersection("Invalid mapping");
Please, ignore this, because exceptions will be removed from memory system. I prefer use return value error codes to simplify interrupts handling.

2023-10-20 21:26 UTC, mmamayka commented on include/besm-666/memory/ram.hpp
> +    virtual ~RAM() {}
Fixed

2023-10-20 21:34 UTC, mmamayka commented on include/besm-666/memory/ram.hpp
> +    std::pair<void *, size_t> getHostAddress(RV64Ptr address) override;
Done

2023-10-21 11:33 UTC, c71n93 approved these changes
@mmamayka Good job!

2023-10-21 12:18 UTC, levBagryansky approved these changes
@mmamayka good

2023-10-23 12:47 UTC, merged