Add CSR infra
BESM-Consortium/BESM-666 pull request #69
Opened 2023-10-18 17:09 UTC by mmamayka

Adds easy configurable & awful implemented Control and Status registers

2023-10-21 10:21 UTC, levBagryansky requested changes

2023-10-23 13:13 UTC, c71n93 approved these changes

2023-10-26 13:44 UTC, levBagryansky requested changes
@mmamayka I did not check csr headers yet

2023-10-26 13:44 UTC, levBagryansky commented on unit_test/util/bit-magic-tests.cpp
> +TEST(InsertMasked, Dummy) {
@mmamayka please add tests to other structures, its not clear enough

2023-10-27 17:09 UTC, mmamayka commented on include/besm-666/config.hpp
> +enum XLEN : RV64UWord { XLEN32 = 1, XLEN64 = 2, XLEN128 = 3 };
Whole file was removed due to further refactoring & development

2023-10-27 17:09 UTC, mmamayka commented on include/besm-666/config.hpp
> +enum class Exception {
Whole file was removed due to further refactoring & development

2023-10-27 17:10 UTC, mmamayka commented on unit_test/util/bit-magic-tests.cpp
> +TEST(InsertMasked, Dummy) {
Structures is a private interface of `InsertMasked` and `ExtractMasked` functions. They should not be used anywhere else.

2023-10-27 17:12 UTC, mmamayka commented on include/besm-666/util/bit-magic.hpp
> +#include <iostream>
Fixed

2023-10-27 18:44 UTC, merged