Assotiative cache implementation
BESM-Consortium/BESM-666 pull request #71
Opened 2023-10-19 18:42 UTC by ivan-egorov42

Tests will be added soon. Pls, have a look @mmamayka

2023-10-19 20:39 UTC, mmamayka requested changes
Looks good, but need to be polished

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    ~CacheEntry(){};
Please, use `= default` syntax.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    void setPayload(PayloadType const &payload) noexcept(
Having to separate method for setting payload and tag, You create probable situation when a payload was changed, but tag wasn't updated. It breaks `CachePayload` the class invariant of payload & tag coherence. I think, we should add tag argument to `setPayload` method and remove `setTag` method.

Also, I think, the `CacheEntry` should be automatically validated when new payload was set. So, I think, we could also remove `validate` method by the same reasons.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    void validate() noexcept;
Please, move functionality of the `validate` method to `setPayload` method.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    void setTag(TagType tag) noexcept;
Please, move functionality of the `setTag` method to `setPayload` method.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +          template <typename, typename> typename TagFunction = TagCount>
We can determine return value type and all parameters type of the `TagFunction`, so we can use simpler definition of it:
```
TagType (*TagFunction) (Payload const&)
```
instead of complicated 
```
template<typename, typename> typename TagFunction
```

This way reduces probability of types mismatch during the `TagFunction` specification.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +          template <typename> typename HashFunction = std::hash,
We can pass template argument `HashType` to the `Cache` class instead of `HastFunction` and deduce hash function definition basing on `PayloadType` and `HashType`:
```
HashType(*HashFunction)(Payload const&);
```

See comment below.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    size_t getSize() noexcept;
I think, we need also add `getSets` and `getWays` methods.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    TagType tag = TagFunction<PayloadType, TagType>{}(payload);
(to the hash & tag functions discussion) I can't imagine scenario when we need tag or hash functions containing any internal state, so I don't see reasons to use functional objects here. I think, we can always use functions directly.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    counters_[set]++;
You can use `counters_[set] = (counters_[set] + 1) % ways_` to compute the next `counters_[set]` value and avoid branch above.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +    cachedData_[set * ways_ + counters_[set]].setPayload(payload);
You forget to use `std::move` here.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +CacheEntry<PayloadType, TagType> const &
To avoid code duplication you can use `const_cast` trick.

2023-10-19 20:39 UTC, mmamayka commented on include/besm-666/util/assotiative-cache.hpp
> +void Cache<PayloadType, TagType, HashFunction, TagFunction>::dump() noexcept {
The instantiation of `Cache` class will be failed if `PayloadType` does not have `operator<<` for `std::ostream`. It's better to create cache iterator, that iterates through all valid elements, and separate class `CacheDumper`, that consumes `std::ostream` like stream in ctor and has method `dump(Cache<...> const& cache)` (see `GPRF` class implementation). In this case only instantiation of `CacheDumper` would be failed.

2023-10-20 10:43 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    ~CacheEntry(){};
Fixed.

2023-10-21 02:03 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    void setPayload(PayloadType const &payload) noexcept(
Changed.

2023-10-21 02:03 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    void validate() noexcept;
Changed.

2023-10-21 02:03 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    void setTag(TagType tag) noexcept;
Changed.

2023-10-21 02:03 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +          template <typename, typename> typename TagFunction = TagCount>
Changed.

2023-10-21 02:03 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +          template <typename> typename HashFunction = std::hash,
Changed.

2023-10-21 02:04 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    size_t getSize() noexcept;
Added.

2023-10-21 02:04 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    TagType tag = TagFunction<PayloadType, TagType>{}(payload);
Changed.

2023-10-21 02:05 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    counters_[set]++;
Fixed.

2023-10-21 02:05 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +    cachedData_[set * ways_ + counters_[set]].setPayload(payload);
Fixed.

2023-10-21 02:05 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +CacheEntry<PayloadType, TagType> const &
Fixed.

2023-10-21 02:05 UTC, ivan-egorov42 commented on include/besm-666/util/assotiative-cache.hpp
> +void Cache<PayloadType, TagType, HashFunction, TagFunction>::dump() noexcept {
Added.

2023-10-21 02:06 UTC, ivan-egorov42 commented
@mmamayka Pls, have a look.

2023-10-21 12:09 UTC, mmamayka reviewed
Looks really good! But unit tests need to be added. At least one dummy unit test that checks, the `Cache` class can be properly instantiated, cache entry can be added and found after. Also, I propose to check a cache replacement correctness by adding N elements with same hash to the cache, where N >= Sets, and looking for them.

2023-10-22 11:10 UTC, ivan-egorov42 commented
@mmamayka pls, have a look.

2023-10-22 21:18 UTC, mmamayka submitted a review, later dismissed
Cool!

2023-10-24 09:22 UTC, levBagryansky approved these changes
@ivan-egorov42 LGTM! please just solve the edit above

2023-10-24 09:22 UTC, levBagryansky commented on unit_test/util/assotiative-cache-tests.cpp
> +    EXPECT_EQ(cache.find(5 * 2).getPayload(), 5);
@ivan-egorov42 maybe better to use `ftag(5)` instead of `5 * 2` here, because `5 * 2` is not clear.

2023-10-31 15:44 UTC, levBagryansky approved these changes
@ivan-egorov42 Nice

2023-10-31 19:15 UTC, mmamayka approved these changes

2023-10-31 19:17 UTC, merged

2023-10-31 19:17 UTC, 0pdd commented
@ivan-egorov42 the puzzle [#77](https://github.com/BESM-Consortium/BESM-666/issues/77) is still not solved.