Added sret and mret instructions to decoder
BESM-Consortium/BESM-666 pull request #74
Opened 2023-10-27 18:46 UTC by levBagryansky

2023-10-27 18:55 UTC, mmamayka reviewed
One little fix and it will be awesome

2023-10-27 21:42 UTC, levBagryansky commented on include/besm-666/decoder/prefetcher.hpp
> +    size_t len_;
@mmamayka done

2023-10-28 11:31 UTC, ivan-egorov42 commented on include/besm-666/memory/mmu.hpp
> +    std::pair<void *, size_t> touchHostAddress(RV64Ptr vaddress);
Mb need `RV64Size` too? Also, where is an implementation?

2023-10-28 11:31 UTC, ivan-egorov42 commented on src/decoder/prefetcher.cpp
> +        return *(RV64UWord *)((uint8_t *)saved_ + vaddress - start_);
Mb using static_cast better?

2023-10-28 11:33 UTC, levBagryansky commented on include/besm-666/memory/mmu.hpp
> +    std::pair<void *, size_t> touchHostAddress(RV64Ptr vaddress);
@ivan-egorov42 I just renamed it here

2023-10-28 12:16 UTC, levBagryansky commented on src/decoder/prefetcher.cpp
> +        return *(RV64UWord *)((uint8_t *)saved_ + vaddress - start_);
@ivan-egorov42 done

2023-10-28 12:17 UTC, levBagryansky commented on include/besm-666/memory/mmu.hpp
> +    std::pair<void *, size_t> touchHostAddress(RV64Ptr vaddress);
@ivan-egorov42 made RV64Size here

2023-10-28 12:57 UTC, c71n93 requested changes

2023-10-28 12:57 UTC, c71n93 commented on src/sim/hart.cpp
>  Hart::Hart(std::shared_ptr<mem::PhysMem> const &pMem,
Could you return it back, please? New version does not optimize anything. It just moves copying of `hookManager` from initializer list to call of `Hart::Hart` constructor.

2023-10-28 13:12 UTC, levBagryansky commented on src/sim/hart.cpp
>  Hart::Hart(std::shared_ptr<mem::PhysMem> const &pMem,
@c71n93 no, this is not worse but maybe better since clang-tidy recommend it

2023-10-28 13:13 UTC, c71n93 commented on src/sim/hart.cpp
>  Hart::Hart(std::shared_ptr<mem::PhysMem> const &pMem,
@levBagryansky prove that it's better, and then you can leave

2023-10-28 13:23 UTC, c71n93 approved these changes

2023-10-28 13:27 UTC, levBagryansky commented on src/sim/hart.cpp
>  Hart::Hart(std::shared_ptr<mem::PhysMem> const &pMem,
@c71n93 this is not worse but maybe better since clang-tidy recommend it

2023-10-28 13:56 UTC, levBagryansky commented
@ivan-egorov42  please check

2023-10-28 16:24 UTC, ivan-egorov42 approved these changes
LGTM

2023-10-28 18:39 UTC, merged